name = "Auralith"
author = "AmeliaCute"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18f068ba2b4dbca1ff82e181e45ef5439725a2bd8ecdc406795f0d07ea8eee66"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
