name = "Auralith"
author = "AmeliaCute"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ee430fa0ad15b24b02cd4d0934940a7698b8e1a15ba6ae32c27a8e3079e0352"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
