name = "Auralith"
author = "AmeliaCute"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f02845f545374feb7345583c48a8629a1c54b554aca00bd62511d0d01d9a175a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
