name = "Auralith"
author = "AmeliaCute"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b0a129e2585fd5174a31ef44b42d415450a10e100c24734bd15a8ca6622a49b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
