name: "Export and Release Modpack (main)"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup env
        run: |
          shopt -s extglob
          mkdir -p build 

      - name: Set up go 
        uses: actions/setup-go@v4
        with: 
          go-version: '1.24.9'

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Copy configs
        run: |
          cp -r config/ Modrinth/
          cp -r config/ CurseForge/
          cp -r kubejs/ Modrinth/
          cp -r kubejs/ CurseForge/

      - name: Export Modrinth
        run: |
          cd Modrinth
          ~/go/bin/packwiz mr export
          cd ..

      - name: Export CurseForge
        run: |
          cd CurseForge
          ~/go/bin/packwiz cf export
          cd ..

      - name: Set up date-based tag
        run: |
          DATE_TAG="v$(date +'%Y%m%d.%H%M')"
          echo "TAG_NAME=$DATE_TAG" >> $GITHUB_ENV
          echo "{tag}=$DATE_TAG"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auralith-${{ env.TAG_NAME }}
          body: "Automated release of ${{ github.ref_name }}."
          generate_release_notes: true
          files: |
            ./Modrinth/*.mrpack
            ./CurseForge/*.zip
          token: ${{ secrets.RELEASE_CD_TOKEN }}

